document.writeln("    <!-- Navigation-->");
document.writeln("    <nav class=\'navbar navbar-expand-lg navbar-dark fixed-top\' id=\'mainNav\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <a class=\'navbar-brand js-scroll-trigger\' href=\'./index.html\'>");
document.writeln("                <img src=\'assets/img/yzu.png\' alt=\'\' class=\'titleImg\' />");
document.writeln("                <h3 class=\'titleWord\'>艾妲資訊培力</h3>");
document.writeln("                <!-- 元智大學「大學社會責任實踐計畫- -->");
document.writeln("            </a>");
document.writeln("            <button class=\'navbar-toggler navbar-toggler-right\' type=\'button\' data-toggle=\'collapse\'");
document.writeln("                data-target=\'#navbarResponsive\' aria-controls=\'navbarResponsive\' aria-expanded=\'false\'");
document.writeln("                aria-label=\'Toggle navigation\'>");
document.writeln("                Menu");
document.writeln("                <i class=\'fas fa-bars ml-1\'></i>");
document.writeln("            </button>");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'navbarResponsive\'>");
document.writeln("                <ul class=\'navbar-nav text-uppercase ml-auto\'>");
document.writeln("                    <li class=\'nav-item dropdown\'>");
document.writeln("                        <a class=\'nav-link dropdown-toggle\' href=\'#\' id=\'navbarDropdownMenuLink\' role=\'button\'");
document.writeln("                            data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            計畫介紹");
document.writeln("                        </a>");
document.writeln("                        <div class=\'dropdown-menu \' aria-labelledby=\'navbarDropdownMenuLink\'>");
document.writeln("                            <a class=\'dropdown-item js-scroll-trigger\' href=\'./index.html#origin\'>艾妲緣起</a>");
document.writeln("                            <a class=\'dropdown-item js-scroll-trigger\' href=\'/index.html#groupMember\'>組織成員</a>");
// document.writeln("                            <a class=\'dropdown-item js-scroll-trigger\' href=\'#about\'>歷屆義工學員</a>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link js-scroll-trigger\' href=\'./teaching.html\'>教學內容</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link js-scroll-trigger\' href=\'./activityRecord.html\'>活動紀錄</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link js-scroll-trigger\' href=\'./experience.html\'>心得感想</a></li>");
document.writeln("                    <li class=\'nav-item\'><a class=\'nav-link js-scroll-trigger\' href=\'./news.html\'>新聞報導</a></li>");
document.writeln("                    <!-- <li class=\'nav-item\'><a class=\'nav-link js-scroll-trigger\' href=\'#contact\'>Contact</a></li> -->");
document.writeln("");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("");