document.writeln("    <!-- bootstrap-table所需的script -->");
// document.writeln("    <link rel=\'stylesheet\' href=\'https://use.fontawesome.com/releases/v5.6.3/css/all.css\' crossorigin=\'anonymous\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.css\'>");
document.writeln("    <script src=\'https://code.jquery.com/jquery-3.3.1.min.js\' crossorigin=\'anonymous\'></script>");
document.writeln("    <script src=\'https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js\'></script>");
document.writeln("    <!-- 動態文字所需的script animejs -->");
document.writeln("    <script src=\'https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js\'></script>");
document.writeln("    <!-- Bootstrap core JS-->");
document.writeln("    <script src=\'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\'></script>");
document.writeln("    <script src=\'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\'></script>");
document.writeln("    <!-- Third party plugin JS-->");
document.writeln("    <script src=\'https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\'></script>");
document.writeln("    <!-- Contact form JS-->");
document.writeln("    <script src=\'assets/mail/jqBootstrapValidation.js\'></script>");
document.writeln("    <script src=\'assets/mail/contact_me.js\'></script>");
document.writeln("    <!-- Core theme JS-->");
document.writeln("    <script src=\'js/all.js\'></script>");